services:
  mysql:
    image: mysql:8.0
    container_name: jaknaeso-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    volumes:
      - ./mysql-data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-time-zone=Asia/Seoul

    networks:
      - jaknaeso-network
    restart: on-failure

  server:
    image: jaknaeso-server.kr.ncr.ntruss.com/jaknaeso:latest
    container_name: jaknaeso-server
    expose:
      - "8080"
    environment:
      DATABASE_HOST: mysql
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ACCESS_TOKEN_EXPIRATION: ${ACCESS_TOKEN_EXPIRATION}
      REFRESH_TOKEN_EXPIRATION: ${REFRESH_TOKEN_EXPIRATION}
      KAKAO_LOGIN_CLIENT_ID: ${KAKAO_LOGIN_CLIENT_ID}
      KAKAO_LOGIN_CLIENT_SECRET: ${KAKAO_LOGIN_CLIENT_SECRET}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      TZ: Asia/Seoul
    volumes:
      - /var/log/jaknaeso:/var/log/jaknaeso
    depends_on:
      - mysql
    networks:
      - jaknaeso-network
      - elastic-network
    restart: on-failure

  nginx:
    image: nginx:latest
    container_name: jaknaeso-nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - mysql
      - server
    volumes:
      - /var/log/nginx:/var/log/nginx
      - ~/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    networks:
      - jaknaeso-network

  certbot:
    image: certbot/certbot:latest
    container_name: jaknaeso-certbot
    depends_on:
      - nginx
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    command: "certonly --webroot -w /var/www/certbot --email jaknaeso@kakao.com --agree-tos --non-interactive -d dev.jaknaeso.kro.kr"
    networks:
      - jaknaeso-network

networks:
  jaknaeso-network:
    driver: bridge
  elastic-network:
    driver: bridge
