version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: jaknaeso-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    volumes:
       - ./mysql-data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-time-zone=Asia/Seoul

    networks:
      - jaknaeso-network
    restart: on-failure

  server:
    image: jaknaeso-server.kr.ncr.ntruss.com/jaknaeso:latest
    container_name: jaknaeso-server
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    depends_on:
      - db
    networks:
      - jaknaeso-network
    restart: on-failure

networks:
  jaknaeso-network:
    driver: bridge

volumes:
  mysql-data: