version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: jaknaeso-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/log/nginx:/var/log/nginx
      - ~/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    networks:
      - nginx-network
      - jaknaeso-dev-network
      - jaknaeso-prod-network
    restart: always

  certbot:
    image: certbot/certbot:latest
    container_name: jaknaeso-certbot
    depends_on:
      - nginx
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    command: "certonly --webroot -w /var/www/certbot --email jaknaeso@kakao.com --agree-tos --non-interactive -d dev.jaknaeso.kro.kr -d prod.jaknaeso.kro.kr"
    networks:
      - nginx-network

networks:
  nginx-network:
    name: nginx-network
    driver: bridge
  jaknaeso-dev-network:
    driver: bridge
  jaknaeso-prod-network:
    driver: bridge