spring:

  datasource:
    url: jdbc:p6spy:mysql://${DATABASE_HOST}/${DATABASE_NAME}
    hikari:
      username: ${DATABASE_USER}
      password: ${DATABASE_PASSWORD}
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

  jpa:
    hibernate:
      ddl-auto: create-drop


logging:
  config: classpath:log/logback-local.xml