spring:

  datasource:
    url: jdbc:mysql://${DATABASE_HOST}/${DATABASE_NAME}
    hikari:
      username: ${DATABASE_USER}
      password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none

logging:
  config: classpath:log/log4j2-dev.yml

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 3600
  refresh-token-expiration: 86400