spring:

  datasource:
    url: jdbc:log4jdbc:p6spy:mysql://${DATABASE_HOST}/${DATABASE_NAME}
    hikari:
      username: ${DATABASE_USER}
      password: ${DATABASE_PASSWORD}
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

  jpa:
    hibernate:
      ddl-auto: create-drop


logging:
  config: classpath:log/log4j2-local.yml
  decorator:
    datasource:
      p6spy:
        enable-logging: true
        multiline: true
        logging: SLF4J
        tracing:
          include-parameter-values: true