spring:
  application:
    name: jaknaeso

  datasource:
    url: jdbc:mysql://localhost:3307/jaknaeso
    hikari:
      username: root
      password: qwer1234

  jpa:
    hibernate:
      ddl-auto: none
