spring:
  application:
    name: jaknaeso

  datasource:
    url: jdbc:mysql://localhost:3307/jaknaeso
    hikari:
      username: root
      password: qwer1234

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none

cors:
  origins:
    api-doc: ${API_DOC_SERVER_HOST}