name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

env:
  SERVICE_NAME: jaknaeso
  BUILD_NUMBER: ${{ github.sha }}-${{ github.run_id }}
  REGISTRY_URL: ${{ secrets.NCP_CONTAINER_REGISTRY_URL }}
  NCP_REGISTRY_USERNAME: ${{ secrets.NCP_ACCESS_KEY }}
  NCP_REGISTRY_PASSWORD: ${{ secrets.NCP_SECRET_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to NCP Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ env.NCP_REGISTRY_USERNAME }}
          password: ${{ env.NCP_REGISTRY_PASSWORD }}

      - name: Build and Push Docker Image
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.REGISTRY_URL }}/${{ env.SERVICE_NAME }}:${{ env.BUILD_NUMBER }}
          build-args: SPRING_PROFILES_ACTIVE=dev
          cache-from: type=registry,ref=${{ env.REGISTRY_URL }}/${{ env.SERVICE_NAME}}:latest
          cache-to: type=inline
