name: CI Pipeline

on:
  pull_request:

env:
  SERVICE_NAME: jaknaeso
  BUILD_NUMBER: ${{ github.sha }}-${{ github.run_id }}
  REGISTRY_URL: ${{ secrets.NCP_CONTAINER_REGISTRY_URL }}
  NCP_REGISTRY_USERNAME: ${{ secrets.NCP_ACCESS_KEY }}
  NCP_REGISTRY_PASSWORD: ${{ secrets.NCP_SECRET_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

