name: Deploy Swagger UI

on:
  push:
    branches:
      - main

jobs:
  build-and-copy:
    if: { { false } } # TODO: 추후 삭제
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Copy OAS to API-doc Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.API_DOC_SERVER_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.API_DOC_SERVER_USERNAME }}
          password: ${{ secrets.API_DOC_SERVER_PASSWORD }}
          source: build/api-spec/openapi3.yaml
          target: ~/app/docs
          strip_components: 2
          overwrite: true

  deploy-to-server:
    needs: build-and-copy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Swagger UI
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.API_DOC_SERVER_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.API_DOC_SERVER_USERNAME }}
          password: ${{ secrets.API_DOC_SERVER_PASSWORD }}
          script: |
            CONTAINER_NAME="api-doc"
            CONTAINER_ID=$(sudo docker ps --filter name=$CONTAINER_NAME -q)
            
            if [ -z "$CONTAINER_ID" ]; then
              sudo docker run -d -p 80:8080 \
                -v ~/app/docs:/usr/share/nginx/html/docs \
                -e URL="/docs/openapi3.yaml" \
                --name $CONTAINER_NAME swaggerapi/swagger-ui:latest
            fi