name : 'Terraform'

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
  pull_request:
    paths:
      - 'terraform/**'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.NCP_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.NCP_SECRET_KEY }}
  TF_VAR_access_key: ${{ secrets.NCP_ACCESS_KEY }}
  TF_VAR_secret_key: ${{ secrets.NCP_SECRET_KEY }}

permissions:
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.NCP_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.NCP_SECRET_KEY }}
        TF_VAR_access_key: ${{ secrets.NCP_ACCESS_KEY }}
        TF_VAR_secret_key: ${{ secrets.NCP_SECRET_KEY }}
      run: terraform init

    - name: Terraform Plan
      env:
        TF_VAR_access_key: ${{ secrets.NCP_ACCESS_KEY }}
        TF_VAR_secret_key: ${{ secrets.NCP_SECRET_KEY }}
      run: terraform plan -input=false

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      env:
        TF_VAR_access_key: ${{ secrets.NCP_ACCESS_KEY }}
        TF_VAR_secret_key: ${{ secrets.NCP_SECRET_KEY }}
      run: terraform apply -auto-approve -input=false
